### ISSUE TITLE
Error during PoseC3D dataset creation

### ISSUE THREAD

**Issue by Rin115** [MitchFuchs/asbar#5]
Hello, I am currently testing whether I can create a training dataset using a small dataset, but I keep encountering the following error.

ｰｰｰｰｰｰｰｰｰｰ
Traceback (most recent call last):
  File "main.py", line 71, in <module>
    main()
  File "main.py", line 67, in main
    use_posec3d(args, cfg)
  File "main.py", line 54, in use_posec3d
    mm.create_training_dataset()
  File "/workspace/asbar/tools/mmaction_utils.py", line 45, in create_training_dataset
    self.create_skeleton_data(split, label_id, label, activity)
  File "/workspace/asbar/tools/mmaction_utils.py", line 63, in create_skeleton_data
    name, ape_id, start, stop, bboxes = activity
ValueError: not enough values to unpack (expected 5, got 1)

ｰｰｰｰｰｰｰｰ

Could it be that the pkl file I created is incorrect?
(Since I couldn’t attach the pkl files, I’ve attached the JSON files instead.)
[activities.json](https://github.com/user-attachments/files/17929860/activities.json)
I am converting the bbox array part of this JSON file into tuple format and then creating the pkl file.

This is a summary of the contents of the JSON file created from the following video datasets.
Train data: 0FhliLmQri, aUNabiDraN
Test data: 4s7Zyrykjs
Val data: 75Hr318myo

I have tried modifying the file multiple times, but the error persists.What could be the cause?

Thank you.

**Comment by Rin115** [comment]
Hello,

When converting from a JSON file to a PKL file, for some reason, one of the elements ended up containing just one item.

I noticed this after loading the PKL file and outputting its structure. By deleting only the element that ended up with a single item, I was able to create the dataset.

Thank you.
